language: php

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

install: composer install

script: composer test

after_script:
  - composer export-coverage

cache:
  directories:
    - vendor

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
